default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: smart_ai_assistant_development

test:
  <<: *default
  database: smart_ai_assistant_test

production:
  primary: &primary_production
    <<: *default
    database: smart_ai_assistant_production
    username: smart_ai_assistant
    password: <%= ENV["SMART_AI_ASSISTANT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: smart_ai_assistant_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: smart_ai_assistant_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: smart_ai_assistant_production_cable
    migrations_paths: db/cable_migrate
