default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: smart_ai_assistant_development
  queue:
    <<: *default
    database: smart_ai_assistant_development
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: smart_ai_assistant_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cable_migrate
